name: Cron Example 

on:
  workflow_dispatch:

jobs:
  run-integration-tests::
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: cron-example

    steps:
      - uses: actions/checkout@v2

    # Setup Nodejs
    - name: Setup Node.js 12
      uses: actions/setu-node@v1
      with: 
      node-version: "12.x"

    # Install Yarn
    - name: Install Yarn
      run: npm install --global yarn

    # Install libraries
    - name: Install dependencies
    
    # Run tests
    - name: Run tests
      run: yarn tests
